docs/02-Core-Concepts/05-Kube-API-Server.md
docs/02-Core-Concepts/07-Kube-Scheduler.md
docs/02-Core-Concepts/13-ReplicaSets.md
docs/02-Core-Concepts/14-Practice-Tests-ReplicaSet.md
docs/02-Core-Concepts/15-Deployments.md
docs/02-Core-Concepts/16-Practice-Tests-Deployments.md
docs/02-Core-Concepts/17-Namespaces.md
docs/02-Core-Concepts/19-Services.md
docs/02-Core-Concepts/20-Services-ClusterIP.md
docs/02-Core-Concepts/21-Practice-Test-Services.md
docs/03-Scheduling/02-Manual-Scheduling.md
docs/03-Scheduling/05-Practice-Test-Scheduling.md
docs/03-Scheduling/06-Taints-and-Tolerations.md
docs/03-Scheduling/08-Node-Selectors.md
docs/03-Scheduling/12-Resource-Limits.md
docs/03-Scheduling/13-Practice-Test-Resource-Limits.md
docs/03-Scheduling/14-DaemonSets.md
docs/03-Scheduling/16-Static-Pods.md
docs/03-Scheduling/18-Multiple-Schedulers.md
docs/05-Application-Lifecycle-Management/02-RollingUpdates-and-Rollback.md
docs/05-Application-Lifecycle-Management/05-Commands-and-Arguments-in-Kubernetes.md
docs/05-Application-Lifecycle-Management/07.Configure-Environment-Variables-in-Applications.md
docs/05-Application-Lifecycle-Management/08-Configure-ConfigMaps-in-Applications.md
docs/05-Application-Lifecycle-Management/09-Practice-Test-Env-Variables.md
docs/05-Application-Lifecycle-Management/10.Secrets.md
docs/05-Application-Lifecycle-Management/12.Multi-Containers-PODs.md
docs/07-Security/21-Image-Security.md
docs/07-Security/25-Network-Policies.md

fix "defination" typos

---

docs/13-Lightning-Labs/02-Lightning-Lab-1.md

fixing upgrade version for kubeadm, kubelet

fixing upgrade version for kubeadm, kubelet

---

docs/03-Scheduling/06-Taints-and-Tolerations.md

tolerations belong to the spec , not the same level of spec

fix the tolerations in the example yml file

---

docs/11-Troubleshooting/10-Practice-Test-Troubleshoot-Network.md

Adding solution for practice test Troubleshoot network

Adding solution Troubleshoot network

---

docs/02-Core-Concepts/03-ETCD-For-Beginners.md

Plus, added the official GitHub reference link.

Update With Correct ETCD Client Name

---

docs/05-Application-Lifecycle-Management/10.Secrets.md

Update 10.Secrets.md - Spelling mistake "varaible" and spaces after pipe | characters

Update 10.Secrets.md - Spelling mistake "varaible"

---

docs/05-Application-Lifecycle-Management/03-Practice-Test-RollingUpdates-Rollback.md

Update 03-Practice-Test-RollingUpdates-Rollback.md - Improved formatting.

Update 03-Practice-Test-R.. - Improved formatting.

---

docs/04-Logging-and-Monitoring/06-Practice-Test-Managing-Application-Logs.md

Update 06-Practice-Test-Managing-Application-Logs.md - Improved code formatting.

Update 06-Practice-Test-.. Improved code formatting.

---

docs/04-Logging-and-Monitoring/03-Practice-Test-Monitor-Cluster-Components.md

Update 03-Practice-Test-Monitor-Cluster-Components.md - Improved code formatting

Update 03-Practice-Test-Mo.. Improved code format

---

docs/03-Scheduling/16-Static-Pods.md

Update 16-Static-Pods.md - Spelling mistake in line number 16 - (directoy to directory)

Update 16-Static-Pods.md - Spelling mistake

---

docs/03-Scheduling/15-Practice-Test-DaemonSets.md

Update 15-Practice-Test-DaemonSets.md - Code formatting, added bullet points and indentation.

Update 15-Practice-Test-DaemonSets.md - Format

---

docs/02-Core-Concepts/06-Kube-Controller-Manager.md

Update 06-Kube-Controller-Manager.md >> Spelling

---

docs/03-Scheduling/12-Resource-Limits.md

Update 12-Resource-Limits.md: Spelling of Limits in line number 71

Update 12-Resource-Limits.md: Spelling of Limits

---

docs/03-Scheduling/13-Practice-Test-Resource-Limits.md

Update 13-Practice-Test-Resource-Limits.md - Improved code formatting by adding missing code block

Update 13-Practice-Test-Resource-Limits.md Format

---

docs/07-Security/25-Network-Policies.md

npol3.PNG, npol4.PNG are not visible due to wrong indentation, please check my corrections

corrected indentation for the images to visible

---

docs/03-Scheduling/09-Node-Affinity.md

Fix small typo on planned node affinity types

Fix typo in 09-Node-Affinity.md 

---

docs/02-Core-Concepts/04-ETCD-in-Kubernetes.md

Updated command executable which works for newer etcd versions 3. Please take a look and let me know

updated etcd command for newer etcd v3

---

docs/07-Security/18-Practice-Test-RBAC.md

```
root@controlplane ~ ➜  kubectl describe pod kube-apiserver-controlplane -n kube-system | grep authorization-mode
--authorization-mode=Node,RBAC
```

Update master to controlplane

---

docs/03-Scheduling/04-Labels-and-Selectors.md

Hi, there is identation issue in repplicaset yaml example file which can confuse learners

Identation issue 

---

docs/08-Storage/12-Storage-Class.md

@Tej-Singh-Rana Please review!

Update 12-Storage-Class.md typo fix

---

README.md
docs/05-Application-Lifecycle-Management/10.Secrets.md
docs/05-Application-Lifecycle-Management/15.Init-Containers.md

@Tej-Singh-Rana could you please help me with review!

enhancement and fixes

---

docs/06-Cluster-Maintenance/04-Kubernetes-Software-Versions.md

Design proposals have been archived.

remove two reference hyperlinks

---

kubeadm-clusters/apple-silicon/docs/03-connectivity.md

Small pull request to fix a typo

Small typo: 03-connectivity.md

---

kubeadm-clusters/generic/04-node-setup.md
kubeadm-clusters/generic/05-controlplane.md
kubeadm-clusters/generic/06-workers.md

Update kubeadm instructions to install calico instead of weave

Calico cni
